#include "stdafx.h"
// Next-turn feedback, progress limits, compaction and budget completion.
#include "coding_tool_loop_internal.h"

namespace action {
namespace agent_detail {

using coding_loop_detail::validation_repair_context;
using coding_loop_detail::save_coding_progress;
using coding_loop_detail::compact_coding_transcript;

void coding_tool_loop_t::build_tool_feedback(coding_turn_t& turn)
{
	acl::json call_json;
	acl::json_node& call_root = call_json.create_node();
	call_root.add_text("name", turn.message.tool.name.c_str());
	call_root.add_text("path", turn.trace.path.c_str());
	if (is_incremental_proposal_tool(turn.message.tool.name) && turn.trace.ok
		&& !turn.message.tool.content.empty())
	{
		// Generated bytes are kept once in the private durable staging state. A
		// digest lets the model correlate calls without paying to resend source.
		call_root.add_number("content_bytes",
			static_cast<long long>(turn.message.tool.content.size()));
		call_root.add_text("content_sha256",
			webcool::ai::agent_workspace_t::content_sha256(
				turn.message.tool.content).c_str());
	}
	if (!turn.message.tool.old_text.empty()) call_root.add_number("old_text_bytes",
		static_cast<long long>(turn.message.tool.old_text.size()));
	if (!turn.message.tool.target_path.empty()) {
		call_root.add_text("target_path", turn.message.tool.target_path.c_str());
	}
	if (!turn.message.tool.query.empty()) {
		call_root.add_text("query", turn.message.tool.query.c_str());
	}
	const std::string call_summary = serialize_json(call_root);
	if (!unresolved_repair_contract.empty() && !turn.output.text.empty() && turn.trace.ok
		&& !repair_review_read_only(turn.message.tool)) {
		// Keep model rationale separately labelled, never promote it to a user requirement.
		const std::string rationale = "\n<assistant_repair_rationale>\n"
			+ webcool::ai::utf8_prefix(turn.output.text, 1536) + "\n</assistant_repair_rationale>\n";
		// Preserve the initial resolution and the latest explanation, with
		// complete wrappers and a fixed bound; small cleanup notes cannot erase it.
		const std::string end_tag = "</assistant_repair_rationale>\n";
		const size_t first_end = repair_contract_findings.find(end_tag);
		if (first_end != std::string::npos)
			repair_contract_findings.resize(first_end + end_tag.size());
		repair_contract_findings += rationale;
	}
	if (!turn.output.text.empty()) recent_findings.append(
		"\n<assistant_findings>\n" + webcool::ai::utf8_prefix(turn.output.text, 8192)
		+ "\n</assistant_findings>\n");
	turn.addition = "\n\n<assistant_tool_call>\n" + call_summary
		+ "\n</assistant_tool_call>\n<tool_result>\n" + turn.tool_result
		+ prompt_text(prompt_id::tool_result_continue, chinese) + turn.automatic_build_feedback;
	if (turn.progress_decision == webcool::ai::agent_progress_replan) {
		next_tool_guidance = prompt_text(prompt_id::progress_replan, chinese);
		turn.addition += next_tool_guidance;
	}
    next_tool_guidance += batch_read_continuation(turn.message.tool.name, turn.tool_result);
	if (turn.validation_failed) {
		if (turn.reconsider_repair) {
			// Attach fresh, complete source within a fixed budget. Oversized
			// or unreadable files still require the existing explicit read path.
			acl::json source_json;
			acl::json_node& sources = source_json.create_array();
			size_t source_bytes = 0, reused_source_files = 0, reviewed_source_bytes = 0;
			webcool::ai::agent_workspace_t review_draft(persistent_draft_root(runtime_task->user_root, project_path, runtime_task->id));
			for (auto it = repair_required_reads.begin(); it != repair_required_reads.end();) {
				std::string relative, content, read_err;
				bool truncated = false;
				if (!project_path_to_draft_path(project_path, it->first, relative)
					|| !review_draft.read(relative, content, truncated, read_err) || truncated
					|| webcool::ai::agent_workspace_t::content_sha256(content) != it->second) { ++it; continue; }
				acl::json record_json;
				acl::json_node& record = record_json.create_node();
				record.add_text("path", it->first.c_str());
				record.add_text("file_sha256", it->second.c_str());
				record.add_text("content", content.c_str());
				const std::string encoded = serialize_json(record);
				if (reviewed_source_bytes + encoded.size() > 32 * 1024) { ++it; continue; }
				reviewed_source_bytes += encoded.size();
				if (webcool::ai::request_has_source(turn.input, it->first, content)
					|| webcool::ai::request_has_source(turn.input, relative, content)) {
					++reused_source_files;
					repair_supplied_versions.insert(*it);
					it = repair_required_reads.erase(it);
					continue;
				}
				source_bytes += encoded.size();
				acl::json_node& entry = sources.add_child(false, true);
				entry.add_text("path", it->first.c_str());
				entry.add_text("file_sha256", it->second.c_str());
				entry.add_text("content", content.c_str());
				repair_supplied_versions.insert(*it);
				it = repair_required_reads.erase(it);
			}
			const std::string supplied = source_bytes == 0 ? "" : std::string(prompt_text(prompt_id::repair_review_supplied, chinese))
				+ "\n<repair_review_sources>\n" + serialize_json(sources) + "\n</repair_review_sources>\n";
			next_tool_guidance = turn.repair_focus + next_tool_guidance + supplied;
			turn.addition += turn.repair_focus + supplied;
			const std::string strategy = std::string(prompt_text(prompt_id::persistent_repair_failure, chinese))
				+ (repair_required_reads.empty() ? "" : repair_review_required(repair_required_reads, chinese));
			next_tool_guidance += strategy;
			turn.addition += strategy;
			acl::json review_json;
			acl::json_node& review_event = review_json.create_node();
			review_event.add_text("event", "repair_strategy_review");
			review_event.add_number("supplied_files", repair_supplied_versions.size() - reused_source_files);
			review_event.add_number("reused_source_files", reused_source_files);
			review_event.add_bool("repair_regressed", repair_failures.regressed());
			review_event.add_bool("repair_alternating", repair_failures.alternating());
			review_event.add_bool("persistent_test_identities", repair_failures.stalled_tests());
			review_event.add_number("still_reported", repair_failures.persisting().size());
			review_event.add_number("returned_failures", repair_failures.returned_failures().size());
			review_event.add_number("supplied_bytes", source_bytes);
			review_event.add_number("remaining_reads", repair_required_reads.size());
			append_runtime_operation_event(runtime_task, review_event);
		}
		next_tool_guidance += prompt_text(prompt_id::validation_next_step, chinese);
		webcool::ai::completion_request_t repair_evidence = turn.input;
		repair_evidence.turn_instructions += next_tool_guidance;
		std::vector<agent_change_proposal_t> repair_changes;
		for (const auto& change : changes) {
			if (!turn.reconsider_repair || repair_required_reads.count(change.path) || repair_supplied_versions.count(change.path))
				repair_changes.push_back(change);
		}
		const std::string repair_context = std::string(prompt_text(prompt_id::validation_repair_guard, chinese))
			+ validation_repair_context(runtime_task->user_root, project_path,
				runtime_task->id, repair_changes, turn.tool_result, 48 * 1024,
				&repair_evidence);
		turn.addition += repair_context;
		// Native replay bypasses the textual transcript. Carry the repair
		// evidence at the next turn's tail rather than silently losing it.
		if (!provider_tool_history.empty()) next_tool_guidance += repair_context;
		proposal_only_turn = false;
	}
	if (turn.draft_cycle) {
		const std::string guidance = prompt_text(prompt_id::draft_cycle, chinese);
		next_tool_guidance += guidance;
		turn.addition += guidance;
	}
}

coding_tool_loop_t::step_t coding_tool_loop_t::check_progress_limit(coding_turn_t& turn)
{
	if (turn.progress_decision == webcool::ai::agent_progress_stop) {
		if (turn.repeated_proposal_failure) {
			err = prompt_text(prompt_id::proposal_repeated_failure, chinese);
			if (!turn.proposal_failures.empty()) err += "\n" + turn.proposal_failures.front();
			final_output = turn.output;
			final_output.text = err;
			final_output.reasoning = accumulated_reasoning;
			final_output.input_tokens = total_input_tokens;
			final_output.cached_input_tokens = total_cached_input_tokens;
			final_output.output_tokens = total_output_tokens;
			final_output.reasoning_tokens = total_reasoning_tokens;
			final_output.latency_ms = total_latency_ms;
			std::string save_err;
			if (!save_coding_progress(progress_store, provider, runtime_task,
				project_path, original_prompt, persistent_transcript + turn.addition,
				accumulated_reasoning, err, executed_tool_calls, save_err)) {
				webcool::ai::ai_log_error("agent.runtime", "save-proposal-failure-checkpoint", save_err);
				err += "\n" + save_err;
				return step_t::failed;
			}
			mark_runtime_recovery_available(runtime_task, progress_store.relative_path());
			return step_t::failed;
		}
		if (!changes.empty()) {
			final_output = turn.output;
			final_output.text = "智能体连续达到管理员设置的无进展操作上限，已停止空转；"
				"现有成果已保存到修订区，未完成的验收项应在下一检查点继续。";
			final_output.reasoning = accumulated_reasoning;
			final_output.input_tokens = total_input_tokens;
			final_output.cached_input_tokens = total_cached_input_tokens;
			final_output.output_tokens = total_output_tokens;
			final_output.reasoning_tokens = total_reasoning_tokens;
			final_output.latency_ms = total_latency_ms;
			rejected_changes = validate_change_proposals(workspace,
				project_path, changes);
			return step_t::completed;
		}
		err = "编程智能体连续重复工具操作，未获得新的有效证据或修订，"
			"已达到无进展操作上限并暂停。请在当前会话继续，结合最后一次"
			"工具诊断调整策略；分析或验证任务可以直接整理已有证据给出结论。";
		// Save the final observation too: it is not yet in the ordinary loop
		// checkpoint. A deliberate user continuation must retain the diagnosis.
		const std::string stopped_transcript = persistent_transcript + turn.addition
			+ prompt_text(prompt_id::progress_resume, chinese);
		std::string save_err;
		if (!save_coding_progress(progress_store, provider, runtime_task,
			project_path, original_prompt, stopped_transcript,
			accumulated_reasoning, err, executed_tool_calls, save_err)) {
			webcool::ai::ai_log_error("agent.runtime",
				"save-no-progress-checkpoint", save_err);
			err += " 恢复记录保存失败：" + save_err;
		} else {
			mark_runtime_recovery_available(runtime_task,
				progress_store.relative_path());
			err += " 诊断与恢复进度已保存。";
		}
		webcool::ai::ai_log_error("agent.runtime", "no-progress-guard", err);
		return step_t::failed;
	}
	return step_t::proceed;
}

bool coding_tool_loop_t::compact_and_checkpoint(coding_turn_t& turn)
{
	// Store source pages once, independently of their batch envelope. Repeated
	// reads must not displace the other pages needed to edit the same file.
	if (!turn.reads_retained) recent_exchanges.append(turn.addition);
	const std::string findings = turn.output.text.empty() ? ""
		: "\n<assistant_findings>\n" + webcool::ai::utf8_prefix(turn.output.text, 8192)
			+ "\n</assistant_findings>\n";
	const size_t uncompressed_bytes = transcript.size() + findings.size() + turn.addition.size();
	auto pending_request = turn.input;
	pending_request.turn_instructions.clear();
	pending_request.user_prompt = validation_capabilities + provider_history_base;
	pending_request.tool_history = provider_tool_history;
	std::string pending_payload;
	const bool measure_native = stateless_responses && !provider_tool_history.empty()
		&& webcool::ai::provider_client_t::serialize_completion_request(provider, pending_request, true, pending_payload);
	const size_t request_bytes = measure_native ? pending_payload.size() : uncompressed_bytes;
	std::string compacted;
	size_t compacted_request_bytes = 0;
	bool compact_now = webcool::ai::agent_context_window_t::needs_compaction(
		request_bytes, 0, compaction_trigger_bytes) || uncompressed_bytes >= kMaxToolTranscriptBytes
		|| request_bytes >= kMaxToolTranscriptBytes;
	if (compact_now) {
		compacted = compact_coding_transcript(initial_prompt,
			changes, traces, recent_findings.text() + recent_exchanges.text()
			+ prompt_text(prompt_id::read_working_set, chinese) + read_context.records() + "</read_working_set>\n"
			+ (turn.progress_decision == webcool::ai::agent_progress_replan
				? prompt_text(prompt_id::repeated_reads, chinese) : ""), chinese);
		compacted_request_bytes = compacted.size();
		if (measure_native) {
			pending_request.tool_history.clear();
			pending_request.user_prompt = validation_capabilities + compacted;
			std::string compacted_payload;
			if (webcool::ai::provider_client_t::serialize_completion_request(provider,
				pending_request, true, compacted_payload)) compacted_request_bytes = compacted_payload.size();
		}
		compact_now = uncompressed_bytes >= kMaxToolTranscriptBytes || request_bytes >= kMaxToolTranscriptBytes
			|| webcool::ai::agent_context_window_t::compaction_saves_enough(request_bytes, compacted_request_bytes);
		if (!compact_now) compaction_trigger_bytes = webcool::ai::agent_context_window_t::next_compaction_limit(
			request_bytes, tool_context_compaction_bytes, turn.addition.size(), kMaxToolTranscriptBytes);
	}
	if (compact_now) {
		read_coverage.clear();
		const size_t previous_bytes = transcript.size();
		persistent_transcript = compacted;
		transcript = persistent_transcript;
		// The guard must track evidence still available to the model, not
		// every source page ever read. Compaction can evict whole files.
		std::vector<std::string> retained_reads;
		collect_observation_signatures("workspace.read_batch",
			"{\"files\":" + read_context.records() + "}", retained_reads);
		progress_supervisor.retain_read_observations(retained_reads);
		// Leave headroom above the retained working set, otherwise a compacted
		// prompt larger than the configured trigger compacts again every turn.
		compaction_trigger_bytes = webcool::ai::agent_context_window_t::next_compaction_limit(
			compacted_request_bytes, tool_context_compaction_bytes, turn.addition.size(),
			kMaxToolTranscriptBytes);
		provider_tool_history.clear();
		read_coverage.clear();
		provider_history_base = transcript;
		acl::json context_json;
		acl::json_node& context_event = context_json.create_node();
		context_event.add_text("event", "context_compacted");
		context_event.add_number("previous_bytes", previous_bytes);
		context_event.add_number("previous_request_bytes", request_bytes);
		context_event.add_number("retained_request_bytes", compacted_request_bytes);
		context_event.add_number("retained_bytes", transcript.size());
		context_event.add_number("retained_exchanges", recent_exchanges.size());
		context_event.add_number("retained_read_files", read_context.files());
		context_event.add_number("retained_read_bytes", read_context.bytes());
		context_event.add_number("next_compaction_bytes", compaction_trigger_bytes);
		append_runtime_operation_event(runtime_task, context_event);
	} else {
		transcript += findings + turn.addition;
		persistent_transcript += findings + turn.addition;
	}
	if (!save_coding_progress(progress_store, provider, runtime_task,
		project_path, original_prompt, persistent_transcript,
		accumulated_reasoning, "", executed_tool_calls, err))
	{
		return false;
	}
	acl::json checkpoint_json;
	acl::json_node& checkpoint_event = checkpoint_json.create_node();
	checkpoint_event.add_text("event", "tool_loop_checkpoint_saved");
	checkpoint_event.add_number("completed_tool_calls",
		static_cast<long long>(executed_tool_calls));
	checkpoint_event.add_number("transcript_bytes",
		static_cast<long long>(persistent_transcript.size()));
	checkpoint_event.add_number("reasoning_bytes",
		static_cast<long long>(accumulated_reasoning.size()));
	checkpoint_event.add_number("pending_change_count",
		static_cast<long long>(changes.size()));
	append_runtime_operation_event(runtime_task, checkpoint_event);
	return true;
}

bool coding_tool_loop_t::finish_budget_boundary()
{
	// Reaching this point is a normal budget boundary.  In particular, a model
	// can ignore the proposal-only tool restriction on the final response turn;
	// that branch deliberately continues, after which the bounded loop ends.  Do
	// not misreport this deterministic exit as an internal crash.
	if (!changes.empty()) {
		const std::string delivery_fingerprint =
			staged_change_fingerprint(changes);
		std::string validation_state = "尚未完成固定构建/测试验证";
		if (delivery_fingerprint == last_validated_fingerprint
			&& last_validation_passed)
		{
			validation_state = successful_validation_summary(last_validation_report, chinese);
		} else {
			agent_tool_trace_t validation_trace;
			validation_trace.name = "workspace.validate";
			validation_trace.path = project_path;
			const std::string validation = validate_staged_draft(
				runtime_task->user_root, project_path, runtime_task->id,
				changes, sandbox_limits, validation_trace);
			traces.push_back(validation_trace);
			record_acceptance_evidence(validation);
			if (validation.find("\"validation_passed\":true")
				!= std::string::npos || validation.find("\"compile_repair_completed\":true") != std::string::npos)
			{
				validation_state = successful_validation_summary(validation, chinese);
			} else if (validation.find("\"commands_executed\":0")
				!= std::string::npos)
			{
				validation_state = "固定验证工具不可用";
			} else {
				validation_state = "固定构建或测试未通过";
			}
		}
		final_output.text = "本轮已达到工具调用额度；现有待审查修订已完整保存。"
			" WebCool 已在额度边界正常结束本轮，不需要从头重新执行。";
		final_output.text += " 当前状态：" + validation_state + "。";
		final_output.reasoning = accumulated_reasoning;
		final_output.input_tokens = total_input_tokens;
		final_output.cached_input_tokens = total_cached_input_tokens;
		final_output.output_tokens = total_output_tokens;
		final_output.reasoning_tokens = total_reasoning_tokens;
		final_output.latency_ms = total_latency_ms;
		rejected_changes = validate_change_proposals(workspace,
			project_path, changes);
		memory_summary = deterministic_delivery_summary(original_prompt,
			changes, validation_state);
		return true;
	}

	// There is nothing reviewable to return, so keep the exact transcript as a
	// continuation point.  This is an expected limit condition rather than the
	// former opaque "terminated unexpectedly" failure.
	err = "本次运行已达到工具调用上限，且尚未产生可审查修订；"
		"已保存断点，请从断点继续当前会话。";
	std::string save_err;
	if (!save_coding_progress(progress_store, provider, runtime_task,
		project_path, original_prompt, persistent_transcript,
		accumulated_reasoning, err, effective_tool_call_limit, save_err))
	{
		webcool::ai::ai_log_error("agent.runtime",
			"save-terminal-tool-boundary", save_err);
		err += " (additionally failed to save recovery progress: "
			+ save_err + ")";
	} else {
		mark_runtime_recovery_available(runtime_task,
			progress_store.relative_path());
		err += " Recovery progress was saved at "
			+ progress_store.relative_path() + ".";
	}
	webcool::ai::ai_log_error("agent.runtime", "tool-loop-budget-boundary", err);
	return false;
}

} // namespace agent_detail
} // namespace action
