if(TARGET webcool_ai_dependencies)
 return()
endif()
find_package(Threads REQUIRED)
if(EXISTS "${OPENSSL_PATH}/lib/libssl.a" AND EXISTS "${OPENSSL_PATH}/lib/libcrypto.a")
 set(_ai_ssl "${OPENSSL_PATH}/lib/libssl.a" "${OPENSSL_PATH}/lib/libcrypto.a")
 set(_ai_ssl_include "${OPENSSL_PATH}/include")
else()
 find_package(OpenSSL REQUIRED)
 set(_ai_ssl OpenSSL::SSL OpenSSL::Crypto)
 set(_ai_ssl_include "${OPENSSL_INCLUDE_DIR}")
endif()
add_library(webcool_ai_dependencies INTERFACE IMPORTED GLOBAL)
set(_ai_acl_dirs ${ACL_LIBRARY_DIRS} "${ACL_PATH}/lib_fiber/lib" "${ACL_PATH}/lib_acl_cpp/lib" "${ACL_PATH}/lib_protocol/lib" "${ACL_PATH}/lib_acl/lib")
set(_ai_libs)
foreach(_name fiber_cpp acl_cpp protocol acl fiber)
 if(_name STREQUAL "acl_cpp")
  set(_win_name lib_acl_cpp)
 elseif(_name STREQUAL "protocol")
  set(_win_name lib_protocol)
 elseif(_name STREQUAL "acl")
  set(_win_name lib_acl)
 else()
  set(_win_name lib${_name})
 endif()
 if(TARGET ${_name}_static)
  list(APPEND _ai_libs ${_name}_static)
 else()
  find_library(AI_${_name}_LIBRARY NAMES ${_name} ${_win_name} PATHS ${_ai_acl_dirs} NO_DEFAULT_PATH)
  if(NOT AI_${_name}_LIBRARY)
   message(FATAL_ERROR "Missing prebuilt ACL library ${_name}; set ACL_PATH or ACL_LIBRARY_DIRS")
  endif()
  list(APPEND _ai_libs "${AI_${_name}_LIBRARY}")
 endif()
endforeach()
target_include_directories(webcool_ai_dependencies INTERFACE
 "${ACL_PATH}/lib_acl/include" "${ACL_PATH}/lib_acl_cpp/include"
 "${ACL_PATH}/lib_protocol/include" "${ACL_PATH}/lib_fiber/c/include"
 "${ACL_PATH}/lib_fiber/cpp/include" ${_ai_ssl_include})
target_link_libraries(webcool_ai_dependencies INTERFACE ${_ai_libs} ${_ai_ssl} Threads::Threads ${CMAKE_DL_LIBS})
if(WIN32)
 target_link_libraries(webcool_ai_dependencies INTERFACE ws2_32 iphlpapi advapi32 crypt32 shell32 user32)
elseif(APPLE)
 target_link_libraries(webcool_ai_dependencies INTERFACE z iconv)
else()
 target_link_libraries(webcool_ai_dependencies INTERFACE z rt)
endif()
